name: Container Build & Push - ColoursWeb
on:
  workflow_dispatch:
  
env:
  IMAGENAME: coloursweb
   
jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: 16    

    - name: Install npm packages 
      run: |
        npm config set package-lock false
        npm i
        npm install -g grunt-cli
      
    - name: run grunt build - to process LESS, compress JS and CSS 
      run: grunt build --verbose

    - name: push any changes
      run: | 
        if expr $(git status --porcelain | wc -l) \> 0
        then 
          git status --porcelain  
          git config user.email "markharrison-GitHubAction@users.noreply.github.com"
          git config user.name "markharrison-GitHubAction"
          git add .
          git commit -m "Grunt Build (Action ${{ github.run_number }})"
          git push
        else 
          echo "Working tree clean. Nothing to commit."
        fi     
        
    - name: format IMAGETAG
      run: |
        echo "IMAGETAG=$(date "+%Y%m%d")-${{github.run_number }}" >> $GITHUB_ENV
        
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["appsettings.json"]'
      env:
        BuildIdentifier: ${{ env.IMAGETAG }}    

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags:  >
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}, 
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGENAME }}:latest,
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}, 
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGENAME }}:latest